name       : libgnome
version    : 2.32.1
release    : 1
source     :
    - http://ftp.acc.umu.se/pub/gnome/sources/libgnome/2.32/libgnome-2.32.1.tar.gz : b9ef58e22708e5ada10757fdb384161b750555d65936103e3191511967d79c17
license    : LGPL-2.0
summary    : This is the non-gui part of the library formerly known as gnome-libs.
description: |
    This is the non-gui part of the library formerly known as gnome-libs.
builddeps  :
    - pkgconfig(gnome-vfs-2.0)
    - pkgconfig(libbonobo-2.0)
    - pkgconfig(gconf-2.0)
    - pkgconfig(libcanberra)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
