name       : libgnome
version    : 2.32.1
release    : 5
source     :
    - https://download.gnome.org/sources/libgnome/2.32/libgnome-2.32.1.tar.gz : b9ef58e22708e5ada10757fdb384161b750555d65936103e3191511967d79c17
license    : LGPL-2.0-or-later
component  : programming.library
summary    : This is the non-gui part of the library formerly known as gnome-libs.
description: |
    This is the non-gui part of the library formerly known as gnome-libs.
builddeps  :
    - pkgconfig(gconf-2.0)
    - pkgconfig(gnome-vfs-2.0)
    - pkgconfig(gtk-doc)
    - pkgconfig(libcanberra)
    - pkgconfig(libbonobo-2.0)
    - pkgconfig(popt)
    - intltool
setup      : |
    %patch -p1 < $pkgfiles/0001-Don-t-use-G_DISABLE_DEPRECATED.patch
    %patch -p1 < $pkgfiles/05_glib-2.54-ftbfs.patch
    %reconfigure --disable-static
build      : |
    %make
install    : |
    %make_install -C libgnome
    %make_install -C monikers
    for dir in doc gnome-data po schemas
    do
        %make_install -C $dir
    done
